def product(name="ProdName", short_code="S001"):
    return {"currencyCode": "USD",
            "includeInBorrowerCycle": "false",
            "useBorrowerCycle": False,
            "digitsAfterDecimal": "2",
            "inMultiplesOf": "0",
            "repaymentFrequencyType": 2,
            "interestRateFrequencyType": 2,
            "amortizationType": 1,
            "interestType": 0,
            "interestCalculationPeriodType": 1,
            "transactionProcessingStrategyId": 1,
            "multiDisburseLoan": False,
            "accountingRule": "1",
            "daysInYearType": 1,
            "daysInMonthType": 1,
            "isInterestRecalculationEnabled": False,
            "preClosureInterestCalculationStrategy": 1,
            "isLinkedToFloatingInterestRates": False,
            "allowVariableInstallments": False,
            "name": name,
            "description": "XXXXXX",
            "shortName": short_code,
            "installmentAmountInMultiplesOf": "1",
            "minPrincipal": "500",
            "principal": "1000",
            "maxPrincipal": "2000",
            "minNumberOfRepayments": "12",
            "numberOfRepayments": "12",
            "maxNumberOfRepayments": "12",
            "minInterestRatePerPeriod": "1",
            "interestRatePerPeriod": "1",
            "maxInterestRatePerPeriod": "3",
            "repaymentEvery": "1",
            "isEqualAmortization": False,
            "principalVariationsForBorrowerCycle": [], "interestRateVariationsForBorrowerCycle": [],
            "numberOfRepaymentVariationsForBorrowerCycle": [], "paymentChannelToFundSourceMappings": [],
            "feeToIncomeAccountMappings": [], "penaltyToIncomeAccountMappings": [], "charges": [],
            "allowAttributeOverrides": {"amortizationType": True, "interestType": True,
                                        "transactionProcessingStrategyId": True, "interestCalculationPeriodType": True,
                                        "inArrearsTolerance": True, "repaymentEvery": True,
                                        "graceOnPrincipalAndInterestPayment": True, "graceOnArrearsAgeing": True},
            "locale": "en", "dateFormat": "dd MMMM yyyy"}


def loan_application(product_id=4, client_id="3", external_id="XXX111"):
    # noinspection SpellCheckingInspection
    return {"clientId": client_id, "productId": product_id, "disbursementData": [], "principal": 1000,
            "loanTermFrequency": 12,
            "loanTermFrequencyType": 2, "numberOfRepayments": 12, "repaymentEvery": 1, "repaymentFrequencyType": 2,
            "interestRatePerPeriod": 1, "amortizationType": 1, "isEqualAmortization": False, "interestType": 0,
            "interestCalculationPeriodType": 1, "allowPartialPeriodInterestCalcualtion": False,
            "transactionProcessingStrategyId": 1, "externalId": external_id, "locale": "en", "dateFormat": "dd MMMM yyyy",
            "loanType": "individual", "expectedDisbursementDate": "06 February 2022",
            "submittedOnDate": "06 February 2022"}
