name: Fineract Spotless Check

on:
  pull_request:
    branches:
      - fiter/africa/dev
  push:
    branches:
      - fiter/africa/dev
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run Spotless Global Check
        run: ./gradlew :spotlessCheck
      - name: Run Spotless Check on Fineract Provider
        run: ./gradlew :fineract-provider:spotlessCheck
